/**
 * EvidenceFigure — annotated synthetic product records that demonstrate
 * the methodology. Two side-by-side mock catalog rows for the same
 * product (Yorkshire honey, 350g): one passes the checks, one fails on
 * Identifiers + Attributes. Hairline rules + mono callouts in the page's
 * existing register.
 *
 * Why this is the right "imagery proves" move (per CLAUDE.md §canon shift
 * 2026-04-26): the prose claims "a missing or invalid identifier is the
 * most common reason a product is suppressed." Here is what that looks
 * like in actual catalog data, with the rule that fired and the score
 * impact on the right side. Type leads, evidence proves.
 *
 * Why NOT Runware/Flux for this figure: it needs perfect text rendering
 * (mono labels, GTIN strings, structured-data keys) and pixel-precise
 * hairline alignment to the design tokens. Generative photoreal will
 * garble UI text and break alignment. The atmospheric still-life
 * generated by Runware lives at the head of the Standard chapter, not
 * here.
 *
 * Pure server component, no JS. Synthetic data — no real merchant
 * implicated. Single semantic tokens (--color-ok, --color-alert) for
 * pass/fail dots so the meaning survives without colour (icon + label).
 */

interface FieldRow {
  label: string;
  pass: { value: string; status: 'ok' | 'partial' };
  fail: { value: string; status: 'alert' | 'partial' | 'ok' };
  failNote?: string;
}

const ROWS: FieldRow[] = [
  {
    label: 'GTIN-13',
    pass: { value: '5012345678900', status: 'ok' },
    fail: { value: '—', status: 'alert' },
    failNote: 'absent → identifiers/checksum fails',
  },
  {
    label: 'Allergens',
    pass: { value: 'contains: nuts (structured)', status: 'ok' },
    fail: { value: '<p>contains nuts</p>', status: 'alert' },
    failNote: 'buried in HTML, not parseable',
  },
  {
    label: 'Brand',
    pass: { value: 'Glenarbor', status: 'ok' },
    fail: { value: '—', status: 'alert' },
    failNote: 'no brand string',
  },
  {
    label: 'Category',
    pass: { value: 'Food, Beverages > Honey', status: 'ok' },
    fail: { value: 'Food', status: 'partial' },
    failNote: 'too shallow, GMC rejects',
  },
  {
    label: 'Title',
    pass: { value: 'Yorkshire wildflower honey 350g', status: 'ok' },
    fail: { value: 'BUY NOW! Best honey deal!!', status: 'alert' },
    failNote: 'fluff demoted by quality classifier',
  },
];

const PASS_SCORE = { identifiers: '18 / 20', attributes: '19 / 20', titles: '14 / 15' };
const FAIL_SCORE = { identifiers: '4 / 20', attributes: '6 / 20', titles: '5 / 15' };

export function EvidenceFigure() {
  return (
    <figure
      aria-labelledby="evidence-figure-caption"
      className="bg-[color:var(--color-paper)]"
      style={{
        marginTop: 'clamp(48px, 6vw, 96px)',
        marginBottom: 'clamp(48px, 6vw, 96px)',
        borderTop: '1px solid var(--color-line)',
        borderBottom: '1px solid var(--color-line)',
        paddingTop: 'clamp(40px, 5vw, 64px)',
        paddingBottom: 'clamp(40px, 5vw, 64px)',
      }}
    >
      <div
        className="mx-auto max-w-[1280px]"
        style={{
          paddingLeft: 'clamp(24px, 4vw, 64px)',
          paddingRight: 'clamp(24px, 4vw, 64px)',
        }}
      >
        <p
          className="font-mono uppercase text-[color:var(--color-mute-2)] mb-3"
          style={{ fontSize: 11, letterSpacing: '0.16em' }}
        >
          Evidence — same product, two records
        </p>
        <h3
          id="evidence-figure-caption"
          className="font-medium text-[color:var(--color-ink)] max-w-[40ch]"
          style={{
            fontSize: 'clamp(20px, 2.2vw, 26px)',
            letterSpacing: '-0.02em',
            lineHeight: 1.2,
            marginBottom: 'clamp(28px, 3.5vw, 48px)',
          }}
        >
          What the seven pillars actually look at, on a single product record.
        </h3>

        <div className="grid md:grid-cols-2 gap-px bg-[color:var(--color-line)] border border-[color:var(--color-line)]">
          <RecordCard
            kind="pass"
            scores={PASS_SCORE}
            rows={ROWS.map((r) => ({ label: r.label, value: r.pass.value, status: r.pass.status, note: undefined }))}
          />
          <RecordCard
            kind="fail"
            scores={FAIL_SCORE}
            rows={ROWS.map((r) => ({ label: r.label, value: r.fail.value, status: r.fail.status, note: r.failNote }))}
          />
        </div>

        <p
          className="text-[color:var(--color-mute)] max-w-[64ch]"
          style={{
            marginTop: 'clamp(24px, 3vw, 32px)',
            fontSize: 13,
            lineHeight: 1.6,
            fontStyle: 'italic',
          }}
        >
          Synthetic example. The same physical jar of honey, two ways of describing it in catalog data. The right-hand record loses ~33 points across Identifiers, Attributes, and Titles before any of the install-gated pillars run.
        </p>
      </div>
    </figure>
  );
}

interface RecordCardProps {
  kind: 'pass' | 'fail';
  rows: { label: string; value: string; status: 'ok' | 'partial' | 'alert'; note?: string }[];
  scores: { identifiers: string; attributes: string; titles: string };
}

function RecordCard({ kind, rows, scores }: RecordCardProps) {
  const heading = kind === 'pass' ? 'How a strong record looks' : 'How a record fails the checks';
  const statusEyebrow = kind === 'pass' ? 'Passes' : 'Fails';
  const eyebrowColor = kind === 'pass' ? 'var(--color-ok)' : 'var(--color-alert)';

  return (
    <div
      className="bg-[color:var(--color-paper)]"
      style={{
        padding: 'clamp(20px, 2.5vw, 32px)',
      }}
    >
      <div className="flex items-center gap-3 mb-2">
        <span
          aria-hidden="true"
          style={{
            width: 8,
            height: 8,
            borderRadius: '50%',
            background: eyebrowColor,
            display: 'inline-block',
          }}
        />
        <p
          className="font-mono uppercase"
          style={{
            fontSize: 11,
            letterSpacing: '0.16em',
            color: eyebrowColor,
          }}
        >
          {statusEyebrow}
        </p>
      </div>

      <p
        className="font-medium text-[color:var(--color-ink)]"
        style={{
          fontSize: 'clamp(16px, 1.4vw, 19px)',
          letterSpacing: '-0.01em',
          marginBottom: 'clamp(20px, 2.4vw, 28px)',
        }}
      >
        {heading}
      </p>

      <dl className="flex flex-col gap-0">
        {rows.map((row, i) => (
          <div
            key={row.label}
            className="grid grid-cols-[110px_1fr] gap-3 py-3"
            style={{
              borderTop: i === 0 ? '1px solid var(--color-line)' : '1px solid var(--color-line-soft)',
            }}
          >
            <dt
              className="font-mono uppercase text-[color:var(--color-mute-2)]"
              style={{ fontSize: 10, letterSpacing: '0.14em', alignSelf: 'start', paddingTop: 2 }}
            >
              {row.label}
            </dt>
            <dd>
              <p
                className="font-mono text-[color:var(--color-ink)] break-words"
                style={{
                  fontSize: 13,
                  lineHeight: 1.45,
                }}
              >
                {row.value}
              </p>
              {row.note ? (
                <p
                  className="text-[color:var(--color-alert)] flex items-start gap-2"
                  style={{
                    fontSize: 11,
                    lineHeight: 1.4,
                    marginTop: 4,
                    fontStyle: 'italic',
                  }}
                >
                  <span aria-hidden="true">&rarr;</span>
                  <span>{row.note}</span>
                </p>
              ) : null}
            </dd>
          </div>
        ))}
      </dl>

      <div
        className="grid grid-cols-3 gap-4"
        style={{
          marginTop: 'clamp(24px, 3vw, 32px)',
          paddingTop: 'clamp(20px, 2.4vw, 24px)',
          borderTop: '1px solid var(--color-line)',
        }}
      >
        <ScoreCell label="Identifiers" value={scores.identifiers} kind={kind} />
        <ScoreCell label="Attributes" value={scores.attributes} kind={kind} />
        <ScoreCell label="Titles" value={scores.titles} kind={kind} />
      </div>
    </div>
  );
}

function ScoreCell({ label, value, kind }: { label: string; value: string; kind: 'pass' | 'fail' }) {
  const valueColor = kind === 'pass' ? 'var(--color-ok)' : 'var(--color-alert)';
  return (
    <div>
      <p
        className="font-mono uppercase text-[color:var(--color-mute-2)]"
        style={{ fontSize: 10, letterSpacing: '0.14em', marginBottom: 4 }}
      >
        {label}
      </p>
      <p
        className="font-mono font-medium"
        style={{
          fontSize: 'clamp(18px, 1.6vw, 22px)',
          letterSpacing: '-0.02em',
          fontVariantNumeric: 'tabular-nums',
          color: valueColor,
        }}
      >
        {value}
      </p>
    </div>
  );
}
