import type { Metadata } from 'next';
import Link from 'next/link';
import { Bracket, SiteFooter } from '@flintmere/ui';
import {
  MARKETING_HOST,
  SCANNER_HOST,
  STANDARDS_HOST,
} from '@/lib/host-routing';

/**
 * /sitemap — human-readable index of every public Flintmere surface.
 *
 * Distinct from `/sitemap.xml` (machine-readable, generated by
 * `apps/scanner/src/app/sitemap.ts`). This is the visitor-facing
 * orientation page — three hosts, the routes on each, the legal
 * footprint, the machine endpoints.
 *
 * Voice register: same as /about — declarative, team voice,
 * restraint-as-composition. One bracket moment in the hero.
 *
 * Source of truth: `apps/scanner/src/lib/host-routing.ts` (host
 * assignments) + `apps/scanner/src/app/sitemap.ts` (XML route list).
 * Adding a new public route: update host-routing.ts MARKETING_ROUTES
 * (or SCANNER_ROUTES / STANDARDS_ROUTES), update sitemap.ts, then
 * mention it here.
 */

export const dynamic = 'force-static';
export const revalidate = 86400;

export const metadata: Metadata = {
  title: 'Sitemap — every public Flintmere surface',
  description:
    `Index of every public Flintmere page across flintmere.com, ${SCANNER_HOST}, and standards.flintmere.com — plus the legal footprint and machine-readable endpoints.`,
  alternates: { canonical: 'https://flintmere.com/sitemap' },
};

interface RouteLink {
  href: string;
  label: string;
  note?: string;
}

const MARKETING_LINKS: RouteLink[] = [
  { href: `https://${MARKETING_HOST}/`, label: 'Home' },
  { href: `https://${MARKETING_HOST}/pricing`, label: 'Pricing' },
  { href: `https://${MARKETING_HOST}/research`, label: 'Research' },
  { href: `https://${MARKETING_HOST}/methodology`, label: 'Methodology' },
  { href: `https://${MARKETING_HOST}/for/food-and-drink`, label: 'For food & drink' },
  { href: `https://${MARKETING_HOST}/for/beauty`, label: 'For beauty' },
  { href: `https://${MARKETING_HOST}/for/apparel`, label: 'For apparel' },
  { href: `https://${MARKETING_HOST}/for/plus`, label: 'Plus tier' },
  { href: `https://${MARKETING_HOST}/about`, label: 'About' },
  { href: `https://${MARKETING_HOST}/founder`, label: 'Founder' },
  { href: `https://${MARKETING_HOST}/support`, label: 'Support' },
  { href: `https://${MARKETING_HOST}/contact`, label: 'Contact' },
];

const SCANNER_LINKS: RouteLink[] = [
  { href: `https://${SCANNER_HOST}/scan`, label: 'Run a scan' },
  { href: `https://${SCANNER_HOST}/catalog-letter`, label: 'The Catalog Letter' },
  { href: `https://${SCANNER_HOST}/bot`, label: 'FlintmereBot' },
  {
    href: `https://${SCANNER_HOST}/scan`,
    label: 'Public scan results',
    note: `at /score/[shop] — generated when a merchant opts in to a public page after their scan completes`,
  },
];

const STANDARDS_LINKS: RouteLink[] = [
  {
    href: `https://${STANDARDS_HOST}/`,
    label: 'Standards (holding page)',
    note: 'the food regulatory taxonomy lands here from June 2026',
  },
];

const LEGAL_LINKS: RouteLink[] = [
  { href: `https://${MARKETING_HOST}/privacy`, label: 'Privacy policy' },
  { href: `https://${MARKETING_HOST}/terms`, label: 'Terms' },
  { href: `https://${MARKETING_HOST}/dpa`, label: 'Data processing addendum' },
  { href: `https://${MARKETING_HOST}/cookies`, label: 'Cookies' },
  { href: `https://${MARKETING_HOST}/security`, label: 'Security' },
];

const MACHINE_LINKS: RouteLink[] = [
  { href: `https://${MARKETING_HOST}/sitemap.xml`, label: 'flintmere.com/sitemap.xml' },
  { href: `https://${MARKETING_HOST}/robots.txt`, label: 'flintmere.com/robots.txt' },
  { href: `https://${SCANNER_HOST}/sitemap.xml`, label: `${SCANNER_HOST}/sitemap.xml` },
  { href: `https://${SCANNER_HOST}/robots.txt`, label: `${SCANNER_HOST}/robots.txt` },
  { href: `https://${STANDARDS_HOST}/sitemap.xml`, label: 'standards.flintmere.com/sitemap.xml' },
  { href: `https://${STANDARDS_HOST}/robots.txt`, label: 'standards.flintmere.com/robots.txt' },
];

function HostSection({
  hostname,
  role,
  description,
  links,
  headingId,
}: {
  hostname: string;
  role: string;
  description: string;
  links: RouteLink[];
  headingId: string;
}) {
  return (
    <section
      aria-labelledby={headingId}
      style={{ marginTop: 'clamp(64px, 8vw, 112px)' }}
    >
      <p
        className="font-mono uppercase"
        style={{
          fontSize: 'clamp(11px, 1vw, 13px)',
          letterSpacing: '0.18em',
          color: 'var(--color-mute)',
          marginBottom: 'clamp(16px, 2vw, 24px)',
        }}
      >
        <span aria-hidden="true">// </span>
        {hostname}
      </p>
      <h2
        id={headingId}
        className="font-sans font-medium tracking-[-0.03em] leading-[1.05] text-[color:var(--color-ink)]"
        style={{
          fontSize: 'clamp(28px, 3.6vw, 48px)',
          marginBottom: 'clamp(16px, 2vw, 24px)',
        }}
      >
        {role}
      </h2>
      <p
        className="font-sans"
        style={{
          fontSize: 'clamp(15px, 1.1vw, 17px)',
          lineHeight: 1.55,
          color: 'var(--color-mute)',
          maxWidth: '52ch',
          marginBottom: 'clamp(28px, 3.5vw, 48px)',
        }}
      >
        {description}
      </p>
      <ul
        className="list-none"
        style={{
          borderTop: '1px solid var(--color-line)',
        }}
      >
        {links.map((link) => (
          <li
            key={`${link.href}__${link.label}`}
            style={{
              borderBottom: '1px solid var(--color-line)',
              paddingTop: 'clamp(14px, 1.6vw, 20px)',
              paddingBottom: 'clamp(14px, 1.6vw, 20px)',
            }}
          >
            <Link
              href={link.href}
              className="font-sans text-[color:var(--color-ink)] hover:text-[color:var(--color-accent)] transition-colors duration-[var(--duration-instant)]"
              style={{
                fontSize: 'clamp(16px, 1.2vw, 19px)',
                lineHeight: 1.4,
                textDecoration: 'none',
              }}
            >
              {link.label}
            </Link>
            {link.note ? (
              <p
                className="font-sans"
                style={{
                  fontSize: 'clamp(13px, 0.95vw, 14px)',
                  lineHeight: 1.5,
                  color: 'var(--color-mute)',
                  marginTop: '6px',
                  maxWidth: '64ch',
                }}
              >
                {link.note}
              </p>
            ) : null}
          </li>
        ))}
      </ul>
    </section>
  );
}

export default function Sitemap() {
  return (
    <>
      <main
        id="main"
        className="flintmere-main bg-[color:var(--color-paper)]"
      >
        <section
          aria-labelledby="sitemap-hero-heading"
          className="mx-auto max-w-[1080px]"
          style={{
            paddingLeft: 'clamp(24px, 4vw, 48px)',
            paddingRight: 'clamp(24px, 4vw, 48px)',
            paddingTop: 'clamp(80px, 10vw, 160px)',
            paddingBottom: 'clamp(48px, 6vw, 80px)',
          }}
        >
          <p
            className="eyebrow-micro"
            style={{ marginBottom: 'clamp(28px, 4vw, 56px)' }}
          >
            Sitemap.
          </p>
          <h1
            id="sitemap-hero-heading"
            className="font-sans font-medium tracking-[-0.035em] leading-[0.98] text-[color:var(--color-ink)]"
            style={{
              fontSize: 'clamp(48px, 7vw, 112px)',
              maxWidth: '14ch',
            }}
          >
            The <Bracket>map</Bracket>.
          </h1>
          <p
            className="font-sans"
            style={{
              fontSize: 'clamp(17px, 1.4vw, 21px)',
              lineHeight: 1.5,
              color: 'var(--color-ink-2, var(--color-ink))',
              maxWidth: '56ch',
              marginTop: 'clamp(32px, 4vw, 56px)',
            }}
          >
            One platform, three subdomains. Marketing lives on{' '}
            <strong>flintmere.com</strong>. The public scanner lives on{' '}
            <strong>{SCANNER_HOST}</strong>. The food regulatory standard
            (Phase 2, June 2026) will live on{' '}
            <strong>standards.flintmere.com</strong>. The Shopify embedded app
            at <strong>app.flintmere.com</strong> is private — it lives behind
            your Shopify admin and isn&rsquo;t indexable.
          </p>
        </section>

        <div
          className="mx-auto max-w-[1080px]"
          style={{
            paddingLeft: 'clamp(24px, 4vw, 48px)',
            paddingRight: 'clamp(24px, 4vw, 48px)',
            paddingBottom: 'clamp(96px, 12vw, 160px)',
          }}
        >
          <HostSection
            hostname={MARKETING_HOST}
            role="Marketing"
            description="Who we are, what we measure, what it costs. The home for positioning, methodology, pricing, and verticals."
            links={MARKETING_LINKS}
            headingId="host-marketing"
          />
          <HostSection
            hostname={SCANNER_HOST}
            role="Scanner"
            description="The public catalog-readiness scan. Run a scan, read the result, book a concierge if you want a human pass."
            links={SCANNER_LINKS}
            headingId="host-scanner"
          />
          <HostSection
            hostname={STANDARDS_HOST}
            role="Standards"
            description="The proprietary food regulatory taxonomy. Phase 1 holds the page; Phase 2 (post-ingestion-engine, June 2026) lands the actual standard."
            links={STANDARDS_LINKS}
            headingId="host-standards"
          />

          <section
            aria-labelledby="legal-heading"
            style={{ marginTop: 'clamp(64px, 8vw, 112px)' }}
          >
            <p
              className="font-mono uppercase"
              style={{
                fontSize: 'clamp(11px, 1vw, 13px)',
                letterSpacing: '0.18em',
                color: 'var(--color-mute)',
                marginBottom: 'clamp(16px, 2vw, 24px)',
              }}
            >
              <span aria-hidden="true">// </span>policy
            </p>
            <h2
              id="legal-heading"
              className="font-sans font-medium tracking-[-0.03em] leading-[1.05] text-[color:var(--color-ink)]"
              style={{
                fontSize: 'clamp(28px, 3.6vw, 48px)',
                marginBottom: 'clamp(16px, 2vw, 24px)',
              }}
            >
              Legal &amp; policy
            </h2>
            <p
              className="font-sans"
              style={{
                fontSize: 'clamp(15px, 1.1vw, 17px)',
                lineHeight: 1.55,
                color: 'var(--color-mute)',
                maxWidth: '52ch',
                marginBottom: 'clamp(28px, 3.5vw, 48px)',
              }}
            >
              Eazy Access Ltd, Companies House 13205428. ICO data-controller
              registration ZC137268 (issued 2026-05-06). Each page lives on
              the marketing host.
            </p>
            <ul
              className="list-none"
              style={{ borderTop: '1px solid var(--color-line)' }}
            >
              {LEGAL_LINKS.map((link) => (
                <li
                  key={link.href}
                  style={{
                    borderBottom: '1px solid var(--color-line)',
                    paddingTop: 'clamp(14px, 1.6vw, 20px)',
                    paddingBottom: 'clamp(14px, 1.6vw, 20px)',
                  }}
                >
                  <Link
                    href={link.href}
                    className="font-sans text-[color:var(--color-ink)] hover:text-[color:var(--color-accent)] transition-colors duration-[var(--duration-instant)]"
                    style={{
                      fontSize: 'clamp(16px, 1.2vw, 19px)',
                      lineHeight: 1.4,
                      textDecoration: 'none',
                    }}
                  >
                    {link.label}
                  </Link>
                </li>
              ))}
            </ul>
          </section>

          <section
            aria-labelledby="machines-heading"
            style={{ marginTop: 'clamp(64px, 8vw, 112px)' }}
          >
            <p
              className="font-mono uppercase"
              style={{
                fontSize: 'clamp(11px, 1vw, 13px)',
                letterSpacing: '0.18em',
                color: 'var(--color-mute)',
                marginBottom: 'clamp(16px, 2vw, 24px)',
              }}
            >
              <span aria-hidden="true">// </span>machines
            </p>
            <h2
              id="machines-heading"
              className="font-sans font-medium tracking-[-0.03em] leading-[1.05] text-[color:var(--color-ink)]"
              style={{
                fontSize: 'clamp(28px, 3.6vw, 48px)',
                marginBottom: 'clamp(16px, 2vw, 24px)',
              }}
            >
              For machines
            </h2>
            <p
              className="font-sans"
              style={{
                fontSize: 'clamp(15px, 1.1vw, 17px)',
                lineHeight: 1.55,
                color: 'var(--color-mute)',
                maxWidth: '52ch',
                marginBottom: 'clamp(28px, 3.5vw, 48px)',
              }}
            >
              Each host serves its own XML sitemap and robots.txt. The marketing
              and standards hosts allow everything except the API. The scanner
              host additionally disallows the raw scoring endpoint.
            </p>
            <ul
              className="list-none"
              style={{ borderTop: '1px solid var(--color-line)' }}
            >
              {MACHINE_LINKS.map((link) => (
                <li
                  key={link.href}
                  style={{
                    borderBottom: '1px solid var(--color-line)',
                    paddingTop: 'clamp(12px, 1.4vw, 18px)',
                    paddingBottom: 'clamp(12px, 1.4vw, 18px)',
                  }}
                >
                  <a
                    href={link.href}
                    className="font-mono text-[color:var(--color-ink)] hover:text-[color:var(--color-accent)] transition-colors duration-[var(--duration-instant)]"
                    style={{
                      fontSize: 'clamp(13px, 1vw, 15px)',
                      letterSpacing: '0.04em',
                      textDecoration: 'none',
                    }}
                  >
                    {link.label}
                  </a>
                </li>
              ))}
            </ul>
          </section>
        </div>
      </main>
      <SiteFooter />
    </>
  );
}
