# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8ca066dd6fb2ed0dc7a027c47cf9a02e"
name = "Flintmere"
application_url = "https://clarinet-swagger-landmark.ngrok-free.dev"
embedded = true

[build]
dev_store_url = "flintmere-dev.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://clarinet-swagger-landmark.ngrok-free.dev/auth/callback",
  "http://localhost:3000/auth/callback"
]

[app_preferences]
url = "https://clarinet-swagger-landmark.ngrok-free.dev/settings"
