/**
 * Snapshot the newest marketing-launch cadence runbook into a TS module
 * the scanner workspace can bundle.
 *
 * Why a snapshot, not a runtime fs.read: `projects/flintmere/runbooks/`
 * lives outside `apps/scanner/`, so Next.js standalone output doesn't
 * trace or include it. The deployed container has no access. Snapshot
 * lifts the content INTO the workspace, where webpack bundles it
 * automatically with no `outputFileTracingIncludes` config gymnastics.
 *
 * Run manually after editing the cadence runbook:
 *   pnpm --filter scanner sync-cadence
 *
 * The output file is committed; the build picks up whatever was last
 * snapshotted. Snapshot date is embedded so the brief can tell the LLM
 * how stale the source is.
 */

import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(here, '..', '..', '..');
const RUNBOOKS_DIR = join(REPO_ROOT, 'projects', 'flintmere', 'runbooks');
const OUT_PATH = join(
  here,
  '..',
  'src',
  'lib',
  'daily-brief',
  'cadence-snapshot.ts',
);
const PATTERN = /-marketing-launch-and-cadence\.md$/;

async function main() {
  const entries = await readdir(RUNBOOKS_DIR);
  const matches = entries.filter((n) => PATTERN.test(n)).sort();
  if (matches.length === 0) {
    throw new Error(`no cadence runbook matches ${PATTERN} in ${RUNBOOKS_DIR}`);
  }
  const newest = matches[matches.length - 1]!;
  const content = await readFile(join(RUNBOOKS_DIR, newest), 'utf8');
  const snapshotAt = new Date().toISOString();

  const ts = [
    '// AUTO-GENERATED by apps/scanner/scripts/sync-cadence.ts',
    '// Do not edit by hand. Run `pnpm --filter scanner sync-cadence`',
    '// after updating the cadence runbook to refresh this file.',
    '',
    `export const cadenceFilename = ${JSON.stringify(newest)};`,
    `export const cadenceSnapshotAt = ${JSON.stringify(snapshotAt)};`,
    `export const cadenceMarkdown = ${JSON.stringify(content)};`,
    '',
  ].join('\n');

  await writeFile(OUT_PATH, ts, 'utf8');
  // eslint-disable-next-line no-console
  console.log(
    JSON.stringify({
      event: 'cadence-snapshot-written',
      source: newest,
      bytes: content.length,
      out: OUT_PATH,
      snapshotAt,
    }),
  );
}

main().catch((err) => {
  // eslint-disable-next-line no-console
  console.error('[sync-cadence] failed', err);
  process.exit(1);
});
